---
- name: restart process_exporter
  systemd:
    daemon_reload: true
    name: process_exporter
    state: restarted
  become: true
  tags: process_exporter

- name: reload process_exporter
  systemd:
    name: process_exporter
    state: reloaded
  become: true
  tags: process_exporter
